[package]
name = "euler"
version = "0.1.0"
authors = ["Brian McCallister <brianm@skife.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
primal = "0.3.0"
itertools = "0.9.0"
num = "0.3.0"
